spring:
  datasource:
    username: root
    password: '!zd3B#;rjQOa'
    url: jdbc:mysql://localhost:3306/homeedu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
    port: 5672
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
logging:
  level:
    org.javaboy.vhr.mapper: debug
fastdfs:
  nginx:
    host: http://192.168.91.128/